import webbrowser
import time

logo = f""" 

$$$$$$$$\ $$$$$$$\   $$$$$$\  $$$$$$$$\ $$$$$$$$\ $$$$$$\  $$$$$$\        $$$$$$$\   $$$$$$\ $$$$$$$$\ 
\__$$  __|$$  __$$\ $$  __$$\ $$  _____|$$  _____|\_$$  _|$$  __$$\       $$  __$$\ $$  __$$\\__$$  __|
   $$ |   $$ |  $$ |$$ /  $$ |$$ |      $$ |        $$ |  $$ /  \__|      $$ |  $$ |$$ /  $$ |  $$ |   
   $$ |   $$$$$$$  |$$$$$$$$ |$$$$$\    $$$$$\      $$ |  $$ |            $$$$$$$\ |$$ |  $$ |  $$ |   
   $$ |   $$  __$$< $$  __$$ |$$  __|   $$  __|     $$ |  $$ |            $$  __$$\ $$ |  $$ |  $$ |   
   $$ |   $$ |  $$ |$$ |  $$ |$$ |      $$ |        $$ |  $$ |  $$\       $$ |  $$ |$$ |  $$ |  $$ |   
   $$ |   $$ |  $$ |$$ |  $$ |$$ |      $$ |      $$$$$$\ \$$$$$$  |      $$$$$$$  | $$$$$$  |  $$ |   
   \__|   \__|  \__|\__|  \__|\__|      \__|      \______| \______/       \_______/  \______/   \__|   
                                                                                                       
                                                                                                       
                                                                                                       
"""

print(logo)

url = input("What is your url? ")

wait_time = int(input(" What is the wait time? ")


x = 1
while True:
  webbrowser.open(url)
  time.sleep(wait_time)
	webbrowser.open_new_tab(url)
	time.sleep(wait_time)	
	webbrowser.open_new_tab(url)
	time.sleep(wait_time)
	webbrowser.open_new_tab(url)
	time.sleep(wait_time)	
	webbrowser.open_new_tab(url)
	time.sleep(wait_time)
	webbrowser.open_new_tab(url)
	time.sleep(wait_time)
	webbrowser.open_new_tab(url)
	time.sleep(wait_time)	
	webbrowser.open_new_tab(url)
	time.sleep(wait_time)
	webbrowser.open_new_tab(url)
	time.sleep(wait_time)	
	webbrowser.open_new_tab(url)
	time.sleep(wait_time)
	webbrowser.open_new_tab(url)
	time.sleep(wait_time)
	webbrowser.open_new_tab(url)
	time.sleep(wait_time)	
	webbrowser.open_new_tab(url)
	time.sleep(wait_time)
	webbrowser.open_new_tab(url)
	time.sleep(wait_time)	
	webbrowser.open_new_tab(url)
	time.sleep(wait_time)
	webbrowser.open_new_tab(url)
	time.sleep(wait_time)
	webbrowser.open_new_tab(url)
	time.sleep(wait_time)	
	webbrowser.open_new_tab(url)
	time.sleep(wait_time)
	webbrowser.open_new_tab(url)
	time.sleep(wait_time)	
	webbrowser.open_new_tab(url)
	time.sleep(wait_time)
	webbrowser.open_new_tab(url)
	time.sleep(wait_time)
	webbrowser.open_new_tab(url)
	time.sleep(wait_time)	
	webbrowser.open_new_tab(url)
	time.sleep(wait_time)
	webbrowser.open_new_tab(url)
	time.sleep(wait_time)	
	webbrowser.open_new_tab(url)
	time.sleep(wait_time)
	webbrowser.open_new_tab(url)
	time.sleep(wait_time)
	webbrowser.open_new_tab(url)
	time.sleep(wait_time)	
	webbrowser.open_new_tab(url)
	time.sleep(wait_time)
	webbrowser.open_new_tab(url)
	time.sleep(wait_time)	
	webbrowser.open_new_tab(url)
	time.sleep(wait_time)
	webbrowser.open_new_tab(url)
	time.sleep(wait_time)
	webbrowser.open_new_tab(url)
	time.sleep(wait_time)	
	webbrowser.open_new_tab(url)
	time.sleep(wait_time)
	webbrowser.open_new_tab(url)
	time.sleep(wait_time)	
	webbrowser.open_new_tab(url)
	time.sleep(wait_time)
	webbrowser.open_new_tab(url)
	time.sleep(wait_time)
	webbrowser.open_new_tab(url)
	time.sleep(wait_time)	
	webbrowser.open_new_tab(url)
	time.sleep(wait_time)
	webbrowser.open_new_tab(url)
	time.sleep(wait_time)	
	webbrowser.open_new_tab(url)
	time.sleep(wait_time)
	webbrowser.open_new_tab(url)
	time.sleep(wait_time)
	webbrowser.open_new_tab(url)
	time.sleep(wait_time)	
	webbrowser.open_new_tab(url)
	time.sleep(wait_time)
	webbrowser.open_new_tab(url)
	time.sleep(wait_time)	
	webbrowser.open_new_tab(url)
	time.sleep(wait_time)
	webbrowser.open_new_tab(url)
	time.sleep(wait_time)
	webbrowser.open_new_tab(url)
	time.sleep(wait_time)	
	webbrowser.open_new_tab(url)
	time.sleep(wait_time)
	webbrowser.open_new_tab(url)
	time.sleep(wait_time)	
	webbrowser.open_new_tab(url)
	time.sleep(wait_time)
	webbrowser.open_new_tab(url)
	time.sleep(wait_time)
	webbrowser.open_new_tab(url)
	time.sleep(wait_time)	
	webbrowser.open_new_tab(url)
	time.sleep(wait_time)
	webbrowser.open_new_tab(url)
	time.sleep(wait_time)	
	webbrowser.open_new_tab(url)
	time.sleep(wait_time)
	webbrowser.open_new_tab(url)
	time.sleep(wait_time)
	webbrowser.open_new_tab(url)
	time.sleep(wait_time)	
	webbrowser.open_new_tab(url)
	time.sleep(wait_time)
	webbrowser.open_new_tab(url)
	time.sleep(wait_time)	
	webbrowser.open_new_tab(url)
	time.sleep(wait_time)
	webbrowser.open_new_tab(url)
	time.sleep(wait_time)
	webbrowser.open_new_tab(url)
	time.sleep(wait_time)	
	webbrowser.open_new_tab(url)
	time.sleep(wait_time)
	webbrowser.open_new_tab(url)
	time.sleep(wait_time)	
	webbrowser.open_new_tab(url)
	time.sleep(wait_time)
	webbrowser.open_new_tab(url)
	time.sleep(wait_time)
	webbrowser.open_new_tab(url)
	time.sleep(wait_time)	
	webbrowser.open_new_tab(url)
	time.sleep(wait_time)
	webbrowser.open_new_tab(url)
	time.sleep(wait_time)	
	webbrowser.open_new_tab(url)
	time.sleep(wait_time)
	webbrowser.open_new_tab(url)
	time.sleep(wait_time)
	webbrowser.open_new_tab(url)
	time.sleep(wait_time)	
	webbrowser.open_new_tab(url)
	time.sleep(wait_time)
	webbrowser.open_new_tab(url)
	time.sleep(wait_time)	
	webbrowser.open_new_tab(url)
	time.sleep(wait_time)
	webbrowser.open_new_tab(url)
	time.sleep(wait_time)
	webbrowser.open_new_tab(url)
	time.sleep(wait_time)	
	webbrowser.open_new_tab(url)
	time.sleep(wait_time)
	webbrowser.open_new_tab(url)
	time.sleep(wait_time)	
	webbrowser.open_new_tab(url)
	time.sleep(wait_time)
	webbrowser.open_new_tab(url)
	time.sleep(wait_time)
	webbrowser.open_new_tab(url)
	time.sleep(wait_time)	
	webbrowser.open_new_tab(url)
	time.sleep(wait_time)
	webbrowser.open_new_tab(url)
	time.sleep(wait_time)	
	webbrowser.open_new_tab(url)
	time.sleep(wait_time)
	webbrowser.open_new_tab(url)
	time.sleep(wait_time)
	webbrowser.open_new_tab(url)
	time.sleep(wait_time)	
	webbrowser.open_new_tab(url)
	time.sleep(wait_time)
	webbrowser.open_new_tab(url)
	time.sleep(wait_time)	
	webbrowser.open_new_tab(url)
	time.sleep(wait_time)
	webbrowser.open_new_tab(url)
	time.sleep(wait_time)
	webbrowser.open_new_tab(url)
	time.sleep(wait_time)	
	webbrowser.open_new_tab(url)
	time.sleep(wait_time)
	webbrowser.open_new_tab(url)
	time.sleep(wait_time)	
	webbrowser.open_new_tab(url)
	time.sleep(wait_time)
	webbrowser.open_new_tab(url)
	time.sleep(wait_time)
	webbrowser.open_new_tab(url)
	time.sleep(wait_time)	
	webbrowser.open_new_tab(url)
	time.sleep(wait_time)
	webbrowser.open_new_tab(url)
	time.sleep(wait_time)	
	webbrowser.open_new_tab(url)
	time.sleep(wait_time)
	x +=1
	
	
